[project]
name = "learn-pytorch"
version = "0.1.0"
description = "pytorch learning exercises"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "torch>=2.5.1",
]
